### ISSUE TITLE
Additional Prerequisites required for installation.

### ISSUE THREAD

**Issue by auyidi1** [Azure-Samples/azure-edge-extensions-retrieval-augmented-generation#1]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Prepare a Windows Host with AKSEE and Azure IoT Operations (AIO) deployed. Download/clone the repo to the dev machine. Deploy the mq-components yaml file in the aio-dapr-deploy subfolders.
`$ kubectl apply -f rag-interface-mq-components.yaml`

### Any log messages given by the failure
> Error message: resource mapping not found for name: "aio-mq-statestore" namespace: "azure-iot-operations" from "rag-interface-mq-components.yaml": no matches for kind "Component" in version "dapr.io/v1alpha1"
ensure CRDs are installed first

### Expected/desired behavior
> Components are successfully deployed to the AKSEE cluster without errors.

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful
Add instructions to install Dapr as a prerequisite:
    ```bash
        helm repo add dapr https://dapr.github.io/helm-charts/
        helm repo update
        helm upgrade --install dapr dapr/dapr --version=1.10 --namespace dapr-system --create-namespace --wait
    ``` 

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ChenCheng368** [comment]
updated README to address the issue.
