### ISSUE TITLE
Dockerfile missing from component folder

### ISSUE THREAD

**Issue by auyidi1** [Azure-Samples/azure-edge-extensions-retrieval-augmented-generation#2]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Download/clone repo to your local dev machine. Attempt to build Dockerfile from the respective components folder.
`cd src\rag-on-edge-interface`
`docker build -t <your container registry url>/rag-on-edge-interface:latest .`

### Any log messages given by the failure
> Docker files are missing from the following components folder:
- rag-on-edge-interface
- rag-on-edge-vectorDB
- rag-on-edge-LLM

### Expected/desired behavior
> Container image is built 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by ChenCheng368** [comment]
updated README to address the issue
