### ISSUE TITLE
README file update

### ISSUE THREAD

**Issue by auyidi1** [Azure-Samples/azure-edge-extensions-retrieval-augmented-generation#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow steps to in the root README file to build images
`docker build -t <CR_url>.rag-on-edge-vectorDB:latest .`
`docker build -t <CR_url>.rag-on-edge-LLM:latest .`

### Any log messages given by the failure
> `ERROR: invalid tag "crragonedge.azurecr.io.rag-on-edge-vectorDB:latest": repository name must be lowercase`

### Expected/desired behavior
> Container image is built with named tag

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> Windows 11

### Mention any other details that might be useful
Define image names to be all lower case strings. Also, container registry host name should be followed by a slash `/`.
`docker build -t <registry host>/rag-on-edge-vectordb:latest .`
`docker build -t <registry host>/rag-on-edge-llm:latest .`

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by katriendg** [comment]
Fixed with PR #8
